export { default as ActionIcon } from './ActionIcon/ActionIcon';
export { default as Cover } from './Cover/Cover';
export { default as Form } from './Form/Form';
export { default as PrivateRoute } from './PrivateRoute/PrivateRoute';
export { default as SearchBox } from './SearchBox/SearchBox';
export { default as Wish } from './Wish/Wish';
export { default as WishList } from './WishList/WishList';
export * from './index';
export { default as Login } from './pages/Login/Login';
export { default as Main } from './pages/Main/Main';
export { default as Page404 } from './pages/Page404/Page404';
export { default as Register } from './pages/Register/Register';
