export const REDUCER_TYPES = {
  //Authentication
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT: "LOGOUT",

  //WISHES
  SET_ALL_WISHES: "SET_ALL_WISHES",
  SET_TRASH_WISHES: "SET_TRASH_WISHES",
  SET_FILTERED_WISHES: "SET_FILTERED_WISHES",
  SET_FILTER: "SET_FILTER",
  SET_IS_FILTER: "SET_IS_FILTER"
}