export const REDUCER_TYPES = {
  //Authentication
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT: "LOGOUT",

  //WISHES
  SET_ALL_WISHES: "SET_ALL_WISHES",
  SET_TRASH_WISHES: "SET_TRASH_WISHES",
  SET_FILTERED_WISHES: "SET_FILTERED_WISHES",
  SET_FILTER: "SET_FILTER",
  SET_IS_FILTER: "SET_IS_FILTER",


  //Databesa actions
  ADD_WISH: "ADD_WISH",
  REMOVE_WISH: "REMOVE_WISH",
  COMPLETE_WISH: "COMPLETE_WISH",
  EDIT_WISH: "EDIT_WISH",
  DELETE_COMPLETED: "DELETE_COMPLETED",
  RECOVER_WISH: "RECOVER_WISH",
  RECOVER_ALL: "RECOVER_ALL",
  DELETE_ALL: "DELETE_ALL",
  EMPTY: "EMPTY"
}